services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.prod
    ports:
      - "8022:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./src/migrations:/code/migrations
      - ./src/alembic.ini:/code/alembic.ini
      - ./src/storage:/code/storage
      - ./src/app:/code/app
      - ./src/.env.prod:/code/.env
      - ./src/certs:/code/certs:ro
      - ./src/app/logs/app.log:/code/app/logs/app.log
      - /etc/localtime:/etc/localtime:ro

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: arq app.core.worker.settings.WorkerSettings
    env_file:
      - ./src/.env.prod
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./src/.env.prod:/code/.env
      - ./src/app:/code/app

  db:
    image: postgres:latest
    env_file:
      - ./src/.env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=dracula
    ports:
      - "8023:8080"
    depends_on:
      db:
        condition: service_healthy
        
  init_scripts:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.prod
    depends_on:
      - db
      - web
    volumes:
      - ./src:/code/src
      - ./src/.env.prod:/code/.env
      - ./src/certs:/code/certs:ro
      - ./src/scripts/sample_data:/code/scripts/sample_data
    # command: >
    #   sh -c "
    #     python -m src.scripts.create_first_superuser &&
    #     python -m src.scripts.create_cities &&
    #     python -m src.scripts.create_categories &&
    #     python -m src.scripts.create_amenities &&
    #     python -m src.scripts.create_rooms
    #   "
    command: >
      sh -c "
        python -m src.scripts.create_amenities 
      "
volumes:
  postgres-data:
  redis-data:
