services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.prod
    # -------- replace with comment if you are using nginx --------
    ports:
      - "8022:8000"
    # expose:
    #   - "8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./src/migrations:/code/migrations
      - ./src/alembic.ini:/code/alembic.ini
      - ./src/storage:/code/storage
      - ./src/app:/code/app
      - ./src/.env.prod:/code/.env.prod
      - ./src/certs:/code/certs:ro
      - ./src/app/logs/app.log:/code/app/logs/app.log
      - /etc/localtime:/etc/localtime:ro

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: arq app.core.worker.settings.WorkerSettings
    env_file:
      - ./src/.env.prod
    depends_on:
      - db
      - redis
    volumes:
      - ./src/.env.prod:/code/.env.prod
      - ./src/app:/code/app

  db:
    image: postgres:latest
    env_file:
      - ./src/.env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # -------- replace with comment to run migrations with docker --------
    expose:
      - "5432"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"

  # -------- create first superuser --------
  create_superuser:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.prod
    depends_on:
      - db
      - web
    command: python -m src.scripts.create_first_superuser
    volumes:
      - ./src:/code/src
      - ./src/.env.prod:/code/.env.prod
      - ./src/certs:/code/certs:ro
  create_cities:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.prod
    depends_on:
      - db
      - web
    command: python -m src.scripts.create_cities
    volumes:
      - ./src:/code/src
      - ./src/.env.prod:/code/.env.prod
      - ./src/certs:/code/certs:ro
      - ./src/scripts/sample_data:/code/scripts/sample_data
  create_categories:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.prod
    depends_on:
      - db
      - web
    command: python -m src.scripts.create_categories
    volumes:
      - ./src:/code/src
      - ./src/.env.prod:/code/.env.prod
      - ./src/certs:/code/certs:ro
      - ./src/scripts/sample_data:/code/scripts/sample_data

  create_amenities:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.prod
    depends_on:
      - db
      - web
    command: python -m src.scripts.create_amenities
    volumes:
      - ./src:/code/src
      - ./src/.env.prod:/code/.env.prod
      - ./src/certs:/code/certs:ro
      - ./src/scripts/sample_data:/code/scripts/sample_data

  #-------- uncomment to create first tier --------
  # create_tier:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./src/.env.prod
  #   depends_on:
  #     - db
  #     - web
  #   command: python -m src.scripts.create_first_tier
  #   volumes:
  #     - ./src:/code/src

  #-------- uncomment to run tests --------
  # pytest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./src/.env
  #   depends_on:
  #     - db
  #     - redis
  #   command: python -m pytest ./tests
  #   volumes:
  #     - .:/code
volumes:
  postgres-data:
  redis-data:
  #pgadmin-data: