"""empty message

Revision ID: 08a17b367aa3
Revises: 2dc7ed5dc85d
Create Date: 2025-03-08 12:56:11.288774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08a17b367aa3"
down_revision: Union[str, None] = "2dc7ed5dc85d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_hotel_infos_email", "hotel_infos", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_hotel_infos_email", "hotel_infos", ["email"]
    )
    # ### end Alembic commands ###
