"""empty message

Revision ID: 2dc7ed5dc85d
Revises: 2de67140a0b8
Create Date: 2025-03-08 11:38:38.354124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dc7ed5dc85d"
down_revision: Union[str, None] = "2de67140a0b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_hotels_hotel_admin_id_partners"),
        "hotels",
        "partners",
        ["hotel_admin_id"],
        ["id"],
    )
    op.drop_column("rules", "is_pet_allowed")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules",
        sa.Column(
            "is_pet_allowed", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_hotels_hotel_admin_id_partners"), "hotels", type_="foreignkey"
    )
    # ### end Alembic commands ###
