"""empty message

Revision ID: d532e73ec959
Revises: d85b8cb84493
Create Date: 2025-03-17 23:02:37.802354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d532e73ec959"
down_revision: Union[str, None] = "d85b8cb84493"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_room_prices_id", table_name="room_prices")
    op.drop_table("room_prices")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_prices",
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guest_quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_room_prices_room_id_rooms"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_room_prices"),
        sa.UniqueConstraint("room_id", name="uq_room_prices_room_id"),
    )
    op.create_index("ix_room_prices_id", "room_prices", ["id"], unique=True)
    # ### end Alembic commands ###
