"""empty message

Revision ID: 082b4ae8b527
Revises: 85ebc70ea722
Create Date: 2025-03-02 23:03:27.131515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "082b4ae8b527"
down_revision: Union[str, None] = "85ebc70ea722"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("guest_quantity", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "fk_bookings_city_id_cities", "bookings", type_="foreignkey"
    )
    op.drop_column("bookings", "adults")
    op.drop_column("bookings", "children")
    op.drop_column("bookings", "city_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "city_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "children", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "bookings",
        sa.Column("adults", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_bookings_city_id_cities", "bookings", "cities", ["city_id"], ["id"]
    )
    op.drop_column("bookings", "guest_quantity")
    # ### end Alembic commands ###
