"""empty message

Revision ID: ad9577c44df8
Revises: 
Create Date: 2025-02-18 17:12:24.167406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad9577c44df8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("total_cost", sa.Integer(), nullable=False)
    )
    op.drop_column("bookings", "total_price")
    op.add_column(
        "hotels", sa.Column("hotel_category_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_hotels_hotel_category_id_hotel_categorys"),
        "hotels",
        "hotel_categorys",
        ["hotel_category_id"],
        ["id"],
    )
    op.add_column(
        "room_types",
        sa.Column("description", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "room_types", sa.Column("start_price", sa.Integer(), nullable=False)
    )
    op.add_column("users", sa.Column("password", sa.String(), nullable=True))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "hashed_password", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "password")
    op.drop_column("room_types", "start_price")
    op.drop_column("room_types", "description")
    op.drop_constraint(
        op.f("fk_hotels_hotel_category_id_hotel_categorys"),
        "hotels",
        type_="foreignkey",
    )
    op.drop_column("hotels", "hotel_category_id")
    op.add_column(
        "bookings",
        sa.Column(
            "total_price", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("bookings", "total_cost")
    # ### end Alembic commands ###
