"""empty message

Revision ID: 3c4e20677fe3
Revises: c91a973224cc
Create Date: 2025-02-27 13:58:41.271848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c4e20677fe3"
down_revision: Union[str, None] = "c91a973224cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_room_prices_id", table_name="room_prices")
    op.drop_table("room_prices")
    op.add_column("rooms", sa.Column("image", sa.String(), nullable=True))
    op.drop_column("rooms", "preview_photo_url")
    op.drop_column("rooms", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column(
            "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "preview_photo_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("rooms", "image")
    op.create_table(
        "room_prices",
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_room_prices_room_id_rooms"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_room_prices"),
    )
    op.create_index("ix_room_prices_id", "room_prices", ["id"], unique=True)
    # ### end Alembic commands ###
