"""create db

Revision ID: f6b16de8b931
Revises: 
Create Date: 2025-03-17 20:51:53.743234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6b16de8b931"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bed_types",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bed_types")),
    )
    op.create_index(op.f("ix_bed_types_id"), "bed_types", ["id"], unique=True)
    op.create_table(
        "countries",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
        sa.UniqueConstraint("code", name=op.f("uq_countries_code")),
        sa.UniqueConstraint("name", name=op.f("uq_countries_name")),
    )
    op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=True)
    op.create_table(
        "hotel_amenity_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_hotel_amenity_categories")
        ),
    )
    op.create_index(
        op.f("ix_hotel_amenity_categories_id"),
        "hotel_amenity_categories",
        ["id"],
        unique=True,
    )
    op.create_table(
        "hotel_categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_hotel_categories_name")),
    )
    op.create_index(
        op.f("ix_hotel_categories_id"), "hotel_categories", ["id"], unique=True
    )
    op.create_table(
        "partners",
        sa.Column("phone_number", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=30), nullable=True),
        sa.Column("last_name", sa.String(length=30), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "is_verified", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "is_fully_registered",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partners")),
        sa.UniqueConstraint("email", name=op.f("uq_partners_email")),
    )
    op.create_index(op.f("ix_partners_id"), "partners", ["id"], unique=True)
    op.create_index(
        op.f("ix_partners_phone_number"),
        "partners",
        ["phone_number"],
        unique=True,
    )
    op.create_table(
        "review_categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_categories")),
    )
    op.create_index(
        op.f("ix_review_categories_id"),
        "review_categories",
        ["id"],
        unique=True,
    )
    op.create_table(
        "room_amenity_categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_amenity_categories")),
        sa.UniqueConstraint(
            "name", name=op.f("uq_room_amenity_categories_name")
        ),
    )
    op.create_index(
        op.f("ix_room_amenity_categories_id"),
        "room_amenity_categories",
        ["id"],
        unique=True,
    )
    op.create_table(
        "room_types",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_types")),
    )
    op.create_index(
        op.f("ix_room_types_id"), "room_types", ["id"], unique=True
    )
    op.create_table(
        "token_blacklists",
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "is_blacklisted",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_blacklists")),
    )
    op.create_index(
        op.f("ix_token_blacklists_id"), "token_blacklists", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_token_blacklists_jti"),
        "token_blacklists",
        ["jti"],
        unique=True,
    )
    op.create_table(
        "cities",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("properties_count", sa.Integer(), nullable=False),
        sa.Column("geocode_lng", sa.Float(), nullable=False),
        sa.Column("geocode_lat", sa.Float(), nullable=False),
        sa.Column("aero_lat", sa.Float(), nullable=False),
        sa.Column("aero_lng", sa.Float(), nullable=False),
        sa.Column("rail_lat", sa.Float(), nullable=False),
        sa.Column("rail_lng", sa.Float(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_cities_country_id_countries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
        sa.UniqueConstraint("name", name=op.f("uq_cities_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_cities_slug")),
    )
    op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=True)
    op.create_table(
        "hotel_amenities",
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "in_hotel", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "is_popular", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "payment_type",
            sa.Enum("FREE", "PAID", name="paymenttype"),
            nullable=False,
        ),
        sa.Column("hotel_amenity_category_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("description", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_amenity_category_id"],
            ["hotel_amenity_categories.id"],
            name=op.f(
                "fk_hotel_amenities_hotel_amenity_category_id_hotel_amenity_categories"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_amenities")),
        sa.UniqueConstraint("icon", name=op.f("uq_hotel_amenities_icon")),
    )
    op.create_index(
        op.f("ix_hotel_amenities_id"), "hotel_amenities", ["id"], unique=True
    )
    op.create_table(
        "hotels",
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("hotel_category_id", sa.Integer(), nullable=False),
        sa.Column("hotel_admin_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("name", sa.JSON(), nullable=False),
        sa.Column("description", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_admin_id"],
            ["partners.id"],
            name=op.f("fk_hotels_hotel_admin_id_partners"),
        ),
        sa.ForeignKeyConstraint(
            ["hotel_category_id"],
            ["hotel_categories.id"],
            name=op.f("fk_hotels_hotel_category_id_hotel_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotels")),
        sa.UniqueConstraint("slug", name=op.f("uq_hotels_slug")),
    )
    op.create_index(op.f("ix_hotels_id"), "hotels", ["id"], unique=True)
    op.create_table(
        "room_amenities",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(length=255), nullable=True),
        sa.Column("room_amenity_category_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_amenity_category_id"],
            ["room_amenity_categories.id"],
            name=op.f(
                "fk_room_amenities_room_amenity_category_id_room_amenity_categories"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_amenities")),
        sa.UniqueConstraint("icon", name=op.f("uq_room_amenities_icon")),
        sa.UniqueConstraint("name", name=op.f("uq_room_amenities_name")),
    )
    op.create_index(
        op.f("ix_room_amenities_id"), "room_amenities", ["id"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("phone_number", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", name="gender_types"),
            nullable=True,
        ),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column(
            "is_verified", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "is_fully_registered",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_users_country_id_countries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True
    )
    op.create_table(
        "hotel_amenity_associations",
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("hotel_amenity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_amenity_id"],
            ["hotel_amenities.id"],
            name=op.f(
                "fk_hotel_amenity_associations_hotel_amenity_id_hotel_amenities"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_hotel_amenity_associations_hotel_id_hotels"),
        ),
        sa.PrimaryKeyConstraint(
            "hotel_id",
            "hotel_amenity_id",
            name=op.f("pk_hotel_amenity_associations"),
        ),
        sa.UniqueConstraint(
            "hotel_id", "hotel_amenity_id", name="uq_hotel_amenity"
        ),
    )
    op.create_table(
        "hotel_images",
        sa.Column("image", sa.String(), nullable=False),
        sa.Column(
            "position", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_hotel_images_hotel_id_hotels"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_images")),
    )
    op.create_index(
        op.f("ix_hotel_images_id"), "hotel_images", ["id"], unique=True
    )
    op.create_table(
        "hotel_infos",
        sa.Column("first_phone_number", sa.String(length=255), nullable=True),
        sa.Column("second_phone_number", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("site_url", sa.String(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_hotel_infos_hotel_id_hotels"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_infos")),
    )
    op.create_index(
        op.f("ix_hotel_infos_id"), "hotel_infos", ["id"], unique=True
    )
    op.create_table(
        "hotel_locations",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("to_airport", sa.Float(), nullable=True),
        sa.Column("to_railway", sa.Float(), nullable=True),
        sa.Column("to_city_center", sa.Float(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
            name=op.f("fk_hotel_locations_city_id_cities"),
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_hotel_locations_hotel_id_hotels"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_locations")),
    )
    op.create_index(
        op.f("ix_hotel_locations_id"), "hotel_locations", ["id"], unique=True
    )
    op.create_table(
        "reviews",
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_reviews_hotel_id_hotels"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reviews_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index(op.f("ix_reviews_id"), "reviews", ["id"], unique=True)
    op.create_table(
        "rooms",
        sa.Column(
            "max_guests", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "quantity", sa.Integer(), server_default="1", nullable=False
        ),
        sa.Column("base_price", sa.Numeric(), nullable=True),
        sa.Column("room_area", sa.Float(), nullable=True),
        sa.Column("room_type_id", sa.Integer(), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_rooms_hotel_id_hotels")
        ),
        sa.ForeignKeyConstraint(
            ["room_type_id"],
            ["room_types.id"],
            name=op.f("fk_rooms_room_type_id_room_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
    )
    op.create_index(op.f("ix_rooms_id"), "rooms", ["id"], unique=True)
    op.create_table(
        "rules",
        sa.Column("check_in_from", sa.String(), nullable=False),
        sa.Column("check_in_until", sa.String(), nullable=True),
        sa.Column("check_out_from", sa.String(), nullable=False),
        sa.Column("check_out_until", sa.String(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_rules_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
    )
    op.create_index(op.f("ix_rules_id"), "rules", ["id"], unique=True)
    op.create_table(
        "user_favorites",
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name=op.f("fk_user_favorites_hotel_id_hotels"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_favorites_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_favorites")),
    )
    op.create_index(
        op.f("ix_user_favorites_id"), "user_favorites", ["id"], unique=True
    )
    op.create_table(
        "review_category_ratings",
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("review_category_id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["review_category_id"],
            ["review_categories.id"],
            name=op.f(
                "fk_review_category_ratings_review_category_id_review_categories"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_review_category_ratings_review_id_reviews"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_category_ratings")),
    )
    op.create_index(
        op.f("ix_review_category_ratings_id"),
        "review_category_ratings",
        ["id"],
        unique=True,
    )
    op.create_table(
        "room_amenity_associations",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("room_amenity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_amenity_id"],
            ["room_amenities.id"],
            name=op.f(
                "fk_room_amenity_associations_room_amenity_id_room_amenities"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_room_amenity_associations_room_id_rooms"),
        ),
        sa.PrimaryKeyConstraint(
            "room_id",
            "room_amenity_id",
            name=op.f("pk_room_amenity_associations"),
        ),
        sa.UniqueConstraint(
            "room_id", "room_amenity_id", name="uq_room_amenity"
        ),
    )
    op.create_table(
        "room_bed_configurations",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("bed_type_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["bed_type_id"],
            ["bed_types.id"],
            name=op.f("fk_room_bed_configurations_bed_type_id_bed_types"),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_room_bed_configurations_room_id_rooms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_bed_configurations")),
    )
    op.create_index(
        op.f("ix_room_bed_configurations_id"),
        "room_bed_configurations",
        ["id"],
        unique=True,
    )
    op.create_table(
        "room_images",
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_room_images_room_id_rooms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_images")),
    )
    op.create_index(
        op.f("ix_room_images_id"), "room_images", ["id"], unique=True
    )
    op.create_table(
        "room_prices",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("guest_quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name=op.f("fk_room_prices_room_id_rooms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_prices")),
    )
    op.create_index(
        op.f("ix_room_prices_id"), "room_prices", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_prices_id"), table_name="room_prices")
    op.drop_table("room_prices")
    op.drop_index(op.f("ix_room_images_id"), table_name="room_images")
    op.drop_table("room_images")
    op.drop_index(
        op.f("ix_room_bed_configurations_id"),
        table_name="room_bed_configurations",
    )
    op.drop_table("room_bed_configurations")
    op.drop_table("room_amenity_associations")
    op.drop_index(
        op.f("ix_review_category_ratings_id"),
        table_name="review_category_ratings",
    )
    op.drop_table("review_category_ratings")
    op.drop_index(op.f("ix_user_favorites_id"), table_name="user_favorites")
    op.drop_table("user_favorites")
    op.drop_index(op.f("ix_rules_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_rooms_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_reviews_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_hotel_locations_id"), table_name="hotel_locations")
    op.drop_table("hotel_locations")
    op.drop_index(op.f("ix_hotel_infos_id"), table_name="hotel_infos")
    op.drop_table("hotel_infos")
    op.drop_index(op.f("ix_hotel_images_id"), table_name="hotel_images")
    op.drop_table("hotel_images")
    op.drop_table("hotel_amenity_associations")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_room_amenities_id"), table_name="room_amenities")
    op.drop_table("room_amenities")
    op.drop_index(op.f("ix_hotels_id"), table_name="hotels")
    op.drop_table("hotels")
    op.drop_index(op.f("ix_hotel_amenities_id"), table_name="hotel_amenities")
    op.drop_table("hotel_amenities")
    op.drop_index(op.f("ix_cities_id"), table_name="cities")
    op.drop_table("cities")
    op.drop_index(
        op.f("ix_token_blacklists_jti"), table_name="token_blacklists"
    )
    op.drop_index(
        op.f("ix_token_blacklists_id"), table_name="token_blacklists"
    )
    op.drop_table("token_blacklists")
    op.drop_index(op.f("ix_room_types_id"), table_name="room_types")
    op.drop_table("room_types")
    op.drop_index(
        op.f("ix_room_amenity_categories_id"),
        table_name="room_amenity_categories",
    )
    op.drop_table("room_amenity_categories")
    op.drop_index(
        op.f("ix_review_categories_id"), table_name="review_categories"
    )
    op.drop_table("review_categories")
    op.drop_index(op.f("ix_partners_phone_number"), table_name="partners")
    op.drop_index(op.f("ix_partners_id"), table_name="partners")
    op.drop_table("partners")
    op.drop_index(
        op.f("ix_hotel_categories_id"), table_name="hotel_categories"
    )
    op.drop_table("hotel_categories")
    op.drop_index(
        op.f("ix_hotel_amenity_categories_id"),
        table_name="hotel_amenity_categories",
    )
    op.drop_table("hotel_amenity_categories")
    op.drop_index(op.f("ix_countries_id"), table_name="countries")
    op.drop_table("countries")
    op.drop_index(op.f("ix_bed_types_id"), table_name="bed_types")
    op.drop_table("bed_types")
    # ### end Alembic commands ###
