"""empty message

Revision ID: 5078bd980804
Revises: ad5b39817985
Create Date: 2025-02-17 21:29:52.617322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5078bd980804"
down_revision: Union[str, None] = "ad5b39817985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("total_price", sa.Integer(), nullable=False)
    )
    op.add_column(
        "bookings", sa.Column("city_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_bookings_city_id_citys"),
        "bookings",
        "citys",
        ["city_id"],
        ["id"],
    )
    op.drop_column("bookings", "price")
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=30), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=30), nullable=False)
    )
    op.add_column("users", sa.Column("birthday", sa.Date(), nullable=False))
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "name", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "birthday")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.add_column(
        "bookings",
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_bookings_city_id_citys"), "bookings", type_="foreignkey"
    )
    op.drop_column("bookings", "city_id")
    op.drop_column("bookings", "total_price")
    # ### end Alembic commands ###
