"""empty message

Revision ID: a3daf863bc83
Revises: e1a8f4d2ad0c
Create Date: 2025-02-28 14:23:02.398811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3daf863bc83"
down_revision: Union[str, None] = "e1a8f4d2ad0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rooms", "max_guests", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "rooms", "max_children", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "rooms", "price_per_night", existing_type=sa.NUMERIC(), nullable=True
    )
    op.drop_constraint(
        "fk_rooms_bed_type_id_bed_types", "rooms", type_="foreignkey"
    )
    op.drop_column("rooms", "bed_type_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column(
            "bed_type_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_rooms_bed_type_id_bed_types",
        "rooms",
        "bed_types",
        ["bed_type_id"],
        ["id"],
    )
    op.alter_column(
        "rooms", "price_per_night", existing_type=sa.NUMERIC(), nullable=False
    )
    op.alter_column(
        "rooms", "max_children", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "rooms", "max_guests", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
