"""empty message

Revision ID: bb1d6044aba2
Revises: 8e70a00a8b92
Create Date: 2025-02-18 13:31:05.180076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb1d6044aba2"
down_revision: Union[str, None] = "8e70a00a8b92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", name="gender_types"),
            server_default=sa.text("'MALE'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("country_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "users", "birthday", existing_type=sa.DATE(), nullable=True
    )
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.create_foreign_key(
        op.f("fk_users_country_id_countrys"),
        "users",
        "countrys",
        ["country_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_country_id_countrys"), "users", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.alter_column(
        "users", "birthday", existing_type=sa.DATE(), nullable=False
    )
    op.drop_column("users", "country_id")
    op.drop_column("users", "gender")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
