"""empty message

Revision ID: 5a46d1444522
Revises: 6665d567a028
Create Date: 2025-03-07 17:40:34.063935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a46d1444522"
down_revision: Union[str, None] = "6665d567a028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_hotel_admin_infos_id", table_name="hotel_admin_infos")
    op.drop_table("hotel_admin_infos")
    op.add_column(
        "hotel_admins",
        sa.Column("phone_number", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "hotel_admins",
        sa.Column("email", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "hotel_admins", sa.Column("password", sa.String(), nullable=True)
    )
    op.add_column(
        "hotel_admins",
        sa.Column("first_name", sa.String(length=30), nullable=False),
    )
    op.add_column(
        "hotel_admins",
        sa.Column("last_name", sa.String(length=30), nullable=False),
    )
    op.create_index(
        op.f("ix_hotel_admins_phone_number"),
        "hotel_admins",
        ["phone_number"],
        unique=True,
    )
    op.create_unique_constraint(
        op.f("uq_hotel_admins_email"), "hotel_admins", ["email"]
    )
    op.drop_constraint(
        "fk_hotel_admins_user_id_users", "hotel_admins", type_="foreignkey"
    )
    op.drop_column("hotel_admins", "user_id")
    op.add_column(
        "hotel_images",
        sa.Column(
            "position", sa.Integer(), server_default="1", nullable=False
        ),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    op.alter_column(
        "rules",
        "check_in_until",
        existing_type=postgresql.TIME(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rules",
        "check_in_until",
        existing_type=postgresql.TIME(),
        nullable=False,
    )
    op.drop_column("hotels", "is_active")
    op.drop_column("hotel_images", "position")
    op.add_column(
        "hotel_admins",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_hotel_admins_user_id_users",
        "hotel_admins",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_hotel_admins_email"), "hotel_admins", type_="unique"
    )
    op.drop_index(
        op.f("ix_hotel_admins_phone_number"), table_name="hotel_admins"
    )
    op.drop_column("hotel_admins", "last_name")
    op.drop_column("hotel_admins", "first_name")
    op.drop_column("hotel_admins", "password")
    op.drop_column("hotel_admins", "email")
    op.drop_column("hotel_admins", "phone_number")
    op.create_table(
        "hotel_admin_infos",
        sa.Column(
            "name", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "first_phone_number",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "second_phone_number",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name="fk_hotel_admin_infos_hotel_id_hotels",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_hotel_admin_infos"),
        sa.UniqueConstraint("name", name="uq_hotel_admin_infos_name"),
    )
    op.create_index(
        "ix_hotel_admin_infos_id", "hotel_admin_infos", ["id"], unique=True
    )
    # ### end Alembic commands ###
