"""empty message

Revision ID: 2de67140a0b8
Revises: e8f842b3299a
Create Date: 2025-03-07 22:33:44.171329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2de67140a0b8"
down_revision: Union[str, None] = "e8f842b3299a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_hotel_admins_hotel_id_hotels", "hotel_admins", type_="foreignkey"
    )
    op.drop_column("hotel_admins", "hotel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotel_admins",
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_hotel_admins_hotel_id_hotels",
        "hotel_admins",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    # ### end Alembic commands ###
