"""empty message

Revision ID: 962aff261250
Revises: 
Create Date: 2025-02-19 15:56:26.207252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "962aff261250"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_amenities_name"), "amenities", ["name"]
    )
    op.create_unique_constraint(
        op.f("uq_amenity_categories_name"), "amenity_categories", ["name"]
    )
    op.add_column(
        "bookings",
        sa.Column(
            "check_in_date", sa.TIMESTAMP(timezone=True), nullable=False
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "check_out_date", sa.TIMESTAMP(timezone=True), nullable=False
        ),
    )
    op.add_column(
        "bookings", sa.Column("total_price", sa.Numeric(), nullable=False)
    )
    op.drop_column("bookings", "total_cost")
    op.drop_column("bookings", "end_date")
    op.drop_column("bookings", "start_date")
    op.create_unique_constraint(
        "uq_hotel_amenity",
        "hotel_amenity_association",
        ["hotel_id", "amenity_id"],
    )
    op.drop_column("room_types", "max_capacity")
    op.drop_column("room_types", "start_price")
    op.add_column(
        "rooms", sa.Column("max_guests", sa.Integer(), nullable=False)
    )
    op.add_column(
        "rooms", sa.Column("price_per_night", sa.Numeric(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "price_per_night")
    op.drop_column("rooms", "max_guests")
    op.add_column(
        "room_types",
        sa.Column(
            "start_price", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "room_types",
        sa.Column(
            "max_capacity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "uq_hotel_amenity", "hotel_amenity_association", type_="unique"
    )
    op.add_column(
        "bookings",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "total_cost", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("bookings", "total_price")
    op.drop_column("bookings", "check_out_date")
    op.drop_column("bookings", "check_in_date")
    op.drop_constraint(
        op.f("uq_amenity_categories_name"),
        "amenity_categories",
        type_="unique",
    )
    op.drop_constraint(op.f("uq_amenities_name"), "amenities", type_="unique")
    # ### end Alembic commands ###
