"""empty message

Revision ID: d85b8cb84493
Revises: 0fa6563f7d9c
Create Date: 2025-03-17 11:32:22.853810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d85b8cb84493"
down_revision: Union[str, None] = "0fa6563f7d9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_room_prices_id", table_name="room_prices")
    op.drop_table("room_prices")
    op.create_foreign_key(
        op.f("fk_hotel_locations_city_id_cities"),
        "hotel_locations",
        "cities",
        ["city_id"],
        ["id"],
    )
    op.alter_column(
        "partners",
        "first_name",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
    )
    op.alter_column(
        "partners",
        "last_name",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
    )
    op.add_column(
        "rooms",
        sa.Column(
            "use_dinamic_price",
            sa.Boolean(),
            server_default="false",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "use_dinamic_price")
    op.alter_column(
        "partners",
        "last_name",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
    )
    op.alter_column(
        "partners",
        "first_name",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
    )
    op.drop_constraint(
        op.f("fk_hotel_locations_city_id_cities"),
        "hotel_locations",
        type_="foreignkey",
    )
    op.create_table(
        "room_prices",
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guest_quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_room_prices_room_id_rooms"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_room_prices"),
    )
    op.create_index("ix_room_prices_id", "room_prices", ["id"], unique=True)
    # ### end Alembic commands ###
