"""empty message

Revision ID: 0fa6563f7d9c
Revises: 5538e20b8fb9
Create Date: 2025-03-14 23:23:49.700315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fa6563f7d9c"
down_revision: Union[str, None] = "5538e20b8fb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bookings_id", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_rules_id", table_name="rules")
    op.drop_table("rules")
    op.create_foreign_key(
        op.f("fk_hotel_amenity_associations_hotel_id_hotels"),
        "hotel_amenity_associations",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_hotel_images_hotel_id_hotels"),
        "hotel_images",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_hotel_infos_hotel_id_hotels"),
        "hotel_infos",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_review_category_ratings_review_id_reviews"),
        "review_category_ratings",
        "reviews",
        ["review_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_room_amenity_associations_room_id_rooms"),
        "room_amenity_associations",
        "rooms",
        ["room_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_room_bed_configurations_room_id_rooms"),
        "room_bed_configurations",
        "rooms",
        ["room_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_room_images_room_id_rooms"),
        "room_images",
        "rooms",
        ["room_id"],
        ["id"],
    )
    op.alter_column(
        "room_prices", "price", existing_type=sa.NUMERIC(), nullable=True
    )
    op.create_foreign_key(
        op.f("fk_room_prices_room_id_rooms"),
        "room_prices",
        "rooms",
        ["room_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_user_favorites_hotel_id_hotels"),
        "user_favorites",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_favorites_hotel_id_hotels"),
        "user_favorites",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_room_prices_room_id_rooms"), "room_prices", type_="foreignkey"
    )
    op.alter_column(
        "room_prices", "price", existing_type=sa.NUMERIC(), nullable=False
    )
    op.drop_constraint(
        op.f("fk_room_images_room_id_rooms"), "room_images", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_room_bed_configurations_room_id_rooms"),
        "room_bed_configurations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_room_amenity_associations_room_id_rooms"),
        "room_amenity_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_review_category_ratings_review_id_reviews"),
        "review_category_ratings",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_hotel_infos_hotel_id_hotels"),
        "hotel_infos",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_hotel_images_hotel_id_hotels"),
        "hotel_images",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_hotel_amenity_associations_hotel_id_hotels"),
        "hotel_amenity_associations",
        type_="foreignkey",
    )
    op.create_table(
        "rules",
        sa.Column(
            "check_in_from", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_in_until", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "check_out_from", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_out_until", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_rules"),
    )
    op.create_index("ix_rules_id", "rules", ["id"], unique=True)
    op.create_table(
        "bookings",
        sa.Column(
            "check_in_date", sa.DATE(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_out_date", sa.DATE(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "CONFIRMED", "CANCELLED", name="bookingstatus"
            ),
            server_default=sa.text("'PENDING'::bookingstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_days", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guest_quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "check_in_date < check_out_date",
            name="ck_bookings_check_in_date_before_check_out_date",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_bookings_room_id_rooms"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_bookings_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_bookings"),
    )
    op.create_index("ix_bookings_id", "bookings", ["id"], unique=True)
    # ### end Alembic commands ###
