"""empty message

Revision ID: fd72d7508c98
Revises: 962aff261250
Create Date: 2025-02-19 23:50:00.517851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd72d7508c98"
down_revision: Union[str, None] = "962aff261250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "amenities",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "amenities",
        "description",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "amenity_categories",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "cities",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "countries",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "hotel_categories",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_hotel_categories_name"), "hotel_categories", ["name"]
    )
    op.add_column(
        "hotels", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.alter_column(
        "hotels",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "hotels",
        "address",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.drop_constraint("uq_hotels_domain", "hotels", type_="unique")
    op.create_unique_constraint(op.f("uq_hotels_slug"), "hotels", ["slug"])
    op.drop_column("hotels", "domain")
    op.alter_column(
        "review_categories",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "room_types",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "room_types",
        "description",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.VARCHAR(length=15),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "phone_number",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "room_types",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "room_types",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "review_categories",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.add_column(
        "hotels",
        sa.Column(
            "domain",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(op.f("uq_hotels_slug"), "hotels", type_="unique")
    op.create_unique_constraint("uq_hotels_domain", "hotels", ["domain"])
    op.alter_column(
        "hotels",
        "address",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "hotels",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_column("hotels", "slug")
    op.drop_constraint(
        op.f("uq_hotel_categories_name"), "hotel_categories", type_="unique"
    )
    op.alter_column(
        "hotel_categories",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "countries",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "cities",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "amenity_categories",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "amenities",
        "description",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "amenities",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
