"""empty message

Revision ID: e8f842b3299a
Revises: 5a46d1444522
Create Date: 2025-03-07 21:23:53.072972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8f842b3299a"
down_revision: Union[str, None] = "5a46d1444522"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels", sa.Column("hotel_admin_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_hotels_hotel_admin_id_hotel_admins"),
        "hotels",
        "hotel_admins",
        ["hotel_admin_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_hotels_hotel_admin_id_hotel_admins"),
        "hotels",
        type_="foreignkey",
    )
    op.drop_column("hotels", "hotel_admin_id")
    # ### end Alembic commands ###
