"""empty message

Revision ID: 8b3d1a8044f7
Revises: f839ceeec904
Create Date: 2025-03-08 13:09:24.687225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b3d1a8044f7"
down_revision: Union[str, None] = "f839ceeec904"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rules",
        "check_in_from",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "rules",
        "check_in_until",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "rules",
        "check_out_from",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "rules",
        "check_out_until",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rules",
        "check_out_until",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
    )
    op.alter_column(
        "rules",
        "check_out_from",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=False,
    )
    op.alter_column(
        "rules",
        "check_in_until",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
    )
    op.alter_column(
        "rules",
        "check_in_from",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
