"""empty message

Revision ID: e1a8f4d2ad0c
Revises: 3c4e20677fe3
Create Date: 2025-02-27 14:55:11.760827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1a8f4d2ad0c"
down_revision: Union[str, None] = "3c4e20677fe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("room_type_variant_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "fk_rooms_room_type_id_room_types", "rooms", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_rooms_room_type_variant_id_room_type_variants"),
        "rooms",
        "room_type_variants",
        ["room_type_variant_id"],
        ["id"],
    )
    op.drop_column("rooms", "room_type_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column(
            "room_type_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_rooms_room_type_variant_id_room_type_variants"),
        "rooms",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_rooms_room_type_id_room_types",
        "rooms",
        "room_types",
        ["room_type_id"],
        ["id"],
    )
    op.drop_column("rooms", "room_type_variant_id")
    # ### end Alembic commands ###
