"""empty message

Revision ID: ca1fd1c4f10c
Revises: 85bde27ca8f4
Create Date: 2025-02-18 13:01:46.428043

"""

from typing import Sequence, Union
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca1fd1c4f10c"
down_revision: Union[str, None] = "85bde27ca8f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels", sa.Column("city_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_hotels_city_id_citys"), "hotels", "citys", ["city_id"], ["id"]
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=255),
        type_=sqlalchemy_utils.types.choice.ChoiceType(length=30),
        nullable=False,
        existing_server_default=sa.text("'USER'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sqlalchemy_utils.types.choice.ChoiceType(length=30),
        type_=sa.VARCHAR(length=255),
        nullable=True,
        existing_server_default=sa.text("'USER'::character varying"),
    )
    op.drop_constraint(
        op.f("fk_hotels_city_id_citys"), "hotels", type_="foreignkey"
    )
    op.drop_column("hotels", "city_id")
    # ### end Alembic commands ###
