"""empty message

Revision ID: d85ab5eeed69
Revises: 7d859de4bb0c
Create Date: 2025-02-28 23:15:02.528581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d85ab5eeed69"
down_revision: Union[str, None] = "7d859de4bb0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_hotel_owners_id", table_name="hotel_owners")
    op.drop_table("hotel_owners")
    op.drop_index("ix_hotel_owner_infos_id", table_name="hotel_owner_infos")
    op.drop_table("hotel_owner_infos")
    op.alter_column(
        "hotels",
        "description",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hotels",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.create_table(
        "hotel_owner_infos",
        sa.Column(
            "name", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column(
            "first_phone_number",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "second_phone_number",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name="fk_hotel_owner_infos_hotel_id_hotels",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_hotel_owner_infos"),
        sa.UniqueConstraint("name", name="uq_hotel_owner_infos_name"),
    )
    op.create_index(
        "ix_hotel_owner_infos_id", "hotel_owner_infos", ["id"], unique=True
    )
    op.create_table(
        "hotel_owners",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name="fk_hotel_owners_hotel_id_hotels"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_hotel_owners_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_hotel_owners"),
    )
    op.create_index("ix_hotel_owners_id", "hotel_owners", ["id"], unique=True)
    # ### end Alembic commands ###
