"""empty message

Revision ID: 50d7c53cc52d
Revises: a843328e457d
Create Date: 2025-02-22 13:21:34.943098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50d7c53cc52d"
down_revision: Union[str, None] = "a843328e457d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bed_types", "max_capacity")
    op.add_column(
        "hotel_amenities",
        sa.Column("in_hotel", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column("rooms", sa.Column("name", sa.String(length=255), nullable=False))
    op.add_column("rooms", sa.Column("price_per_night", sa.Numeric(), nullable=False))
    op.add_column("rooms", sa.Column("room_area", sa.Float(), nullable=True))
    op.add_column("rooms", sa.Column("bed_type_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_rooms_bed_type_id_bed_types"),
        "rooms",
        "bed_types",
        ["bed_type_id"],
        ["id"],
    )
    op.drop_column("rooms", "base_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("base_price", sa.NUMERIC(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_rooms_bed_type_id_bed_types"), "rooms", type_="foreignkey"
    )
    op.drop_column("rooms", "bed_type_id")
    op.drop_column("rooms", "room_area")
    op.drop_column("rooms", "price_per_night")
    op.drop_column("rooms", "name")
    op.drop_column("hotel_amenities", "in_hotel")
    op.add_column(
        "bed_types",
        sa.Column("max_capacity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
