"""empty message

Revision ID: 9b55361c4b56
Revises: d532e73ec959
Create Date: 2025-03-19 12:29:02.721145

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b55361c4b56"
down_revision: Union[str, None] = "d532e73ec959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_room_prices_id", table_name="room_prices")
    op.drop_table("room_prices")
    op.drop_index("ix_rules_id", table_name="rules")
    op.drop_table("rules")
    op.add_column(
        "bookings", sa.Column("special_requests", sa.Text(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_hotel_amenity_associations_hotel_amenity_id_hotel_amenities"),
        "hotel_amenity_associations",
        "hotel_amenities",
        ["hotel_amenity_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_hotel_amenity_associations_hotel_id_hotels"),
        "hotel_amenity_associations",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_hotel_images_hotel_id_hotels"),
        "hotel_images",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_hotel_infos_hotel_id_hotels"),
        "hotel_infos",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_hotel_locations_hotel_id_hotels"),
        "hotel_locations",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_reviews_hotel_id_hotels"),
        "reviews",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.add_column(
        "room_images",
        sa.Column(
            "position", sa.Integer(), server_default="1", nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("fk_rooms_hotel_id_hotels"),
        "rooms",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_user_favorites_hotel_id_hotels"),
        "user_favorites",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_favorites_hotel_id_hotels"),
        "user_favorites",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_rooms_hotel_id_hotels"), "rooms", type_="foreignkey"
    )
    op.drop_column("room_images", "position")
    op.drop_constraint(
        op.f("fk_reviews_hotel_id_hotels"), "reviews", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_hotel_locations_hotel_id_hotels"),
        "hotel_locations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_hotel_infos_hotel_id_hotels"),
        "hotel_infos",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_hotel_images_hotel_id_hotels"),
        "hotel_images",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_hotel_amenity_associations_hotel_id_hotels"),
        "hotel_amenity_associations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_hotel_amenity_associations_hotel_amenity_id_hotel_amenities"),
        "hotel_amenity_associations",
        type_="foreignkey",
    )
    op.drop_column("bookings", "special_requests")
    op.create_table(
        "rules",
        sa.Column(
            "check_in_from", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_in_until", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "check_out_from", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_out_until", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name="fk_rules_hotel_id_hotels"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_rules"),
    )
    op.create_index("ix_rules_id", "rules", ["id"], unique=True)
    op.create_table(
        "room_prices",
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guest_quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_room_prices_room_id_rooms"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_room_prices"),
    )
    op.create_index("ix_room_prices_id", "room_prices", ["id"], unique=True)
    # ### end Alembic commands ###
