"""empty message

Revision ID: c91a973224cc
Revises: 50d7c53cc52d
Create Date: 2025-02-25 12:58:55.876563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c91a973224cc"
down_revision: Union[str, None] = "50d7c53cc52d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_images_id", table_name="images")
    op.drop_table("images")
    op.add_column(
        "bookings", sa.Column("adults", sa.Integer(), nullable=False)
    )
    op.add_column(
        "bookings", sa.Column("children", sa.Integer(), nullable=False)
    )
    op.add_column(
        "hotel_amenities",
        sa.Column("icon", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_hotel_amenities_icon"), "hotel_amenities", ["icon"]
    )
    op.add_column(
        "hotels", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.add_column("hotels", sa.Column("image", sa.String(), nullable=True))
    op.add_column(
        "hotels",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "hotels",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.create_unique_constraint(op.f("uq_hotels_slug"), "hotels", ["slug"])
    op.drop_constraint(
        "fk_hotels_location_id_locations", "hotels", type_="foreignkey"
    )
    op.drop_column("hotels", "location_id")
    op.drop_column("hotels", "preview_photo_path")
    op.add_column(
        "locations", sa.Column("hotel_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "fk_locations_country_id_countries", "locations", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_locations_hotel_id_hotels"),
        "locations",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.drop_column("locations", "country_id")
    op.add_column(
        "room_amenities",
        sa.Column("icon", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_room_amenities_icon"), "room_amenities", ["icon"]
    )
    op.drop_column("rooms", "rating")
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("USER", "ADMIN", name="role_types"),
            server_default=sa.text("'USER'::role_types"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'5'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("uq_room_amenities_icon"), "room_amenities", type_="unique"
    )
    op.drop_column("room_amenities", "icon")
    op.add_column(
        "locations",
        sa.Column(
            "country_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_locations_hotel_id_hotels"), "locations", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_locations_country_id_countries",
        "locations",
        "countries",
        ["country_id"],
        ["id"],
    )
    op.drop_column("locations", "hotel_id")
    op.add_column(
        "hotels",
        sa.Column(
            "preview_photo_path",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "location_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_hotels_location_id_locations",
        "hotels",
        "locations",
        ["location_id"],
        ["id"],
    )
    op.drop_constraint(op.f("uq_hotels_slug"), "hotels", type_="unique")
    op.drop_column("hotels", "updated_at")
    op.drop_column("hotels", "created_at")
    op.drop_column("hotels", "image")
    op.drop_column("hotels", "slug")
    op.drop_constraint(
        op.f("uq_hotel_amenities_icon"), "hotel_amenities", type_="unique"
    )
    op.drop_column("hotel_amenities", "icon")
    op.drop_column("bookings", "children")
    op.drop_column("bookings", "adults")
    op.create_table(
        "images",
        sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name="fk_images_hotel_id_hotels"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_images"),
    )
    op.create_index("ix_images_id", "images", ["id"], unique=True)
    # ### end Alembic commands ###
