"""empty message

Revision ID: 85ec18331bf6
Revises: f02c12f76404
Create Date: 2025-03-09 02:06:30.614192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85ec18331bf6"
down_revision: Union[str, None] = "f02c12f76404"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        nullable=True,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        nullable=False,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        nullable=False,
    )
    # ### end Alembic commands ###
