"""empty message

Revision ID: 179189fe6b02
Revises: b76b67ab21dd
Create Date: 2025-03-09 14:41:49.503530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "179189fe6b02"
down_revision: Union[str, None] = "b76b67ab21dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("SUPERADMIN", "USER", name="user_role_types"),
            server_default=sa.text("'USER'::user_role_types"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
