"""empty message

Revision ID: 23669426e7fc
Revises: 9b55361c4b56
Create Date: 2025-03-21 23:05:10.429920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23669426e7fc"
down_revision: Union[str, None] = "9b55361c4b56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_room_prices_id", table_name="room_prices")
    op.drop_table("room_prices")
    op.add_column(
        "bookings", sa.Column("hotel_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_bookings_hotel_id_hotels"),
        "bookings",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.create_unique_constraint(
        "unique_room_type_hotel", "rooms", ["room_type_id", "hotel_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_room_type_hotel", "rooms", type_="unique")
    op.drop_constraint(
        op.f("fk_bookings_hotel_id_hotels"), "bookings", type_="foreignkey"
    )
    op.drop_column("bookings", "hotel_id")
    op.create_table(
        "room_prices",
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guest_quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_room_prices_room_id_rooms"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_room_prices"),
    )
    op.create_index("ix_room_prices_id", "room_prices", ["id"], unique=True)
    # ### end Alembic commands ###
