"""empty message

Revision ID: 85ebc70ea722
Revises: d85ab5eeed69
Create Date: 2025-03-02 20:47:25.724146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85ebc70ea722"
down_revision: Union[str, None] = "d85ab5eeed69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("total_days", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "bookings",
        "check_in_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "check_out_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.add_column(
        "locations", sa.Column("to_airport", sa.Float(), nullable=True)
    )
    op.add_column(
        "locations", sa.Column("to_railway", sa.Float(), nullable=True)
    )
    op.add_column(
        "locations", sa.Column("to_city_center", sa.Float(), nullable=True)
    )
    op.add_column(
        "rooms", sa.Column("base_price", sa.Numeric(), nullable=True)
    )
    op.drop_column("rooms", "price_per_night")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column(
            "price_per_night", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("rooms", "base_price")
    op.drop_column("locations", "to_city_center")
    op.drop_column("locations", "to_railway")
    op.drop_column("locations", "to_airport")
    op.alter_column(
        "bookings",
        "check_out_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "check_in_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_column("bookings", "total_days")
    # ### end Alembic commands ###
