"""empty message

Revision ID: 21ddc10db116
Revises: efe3d2ddb5a0
Create Date: 2025-02-20 02:31:02.659089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21ddc10db116"
down_revision: Union[str, None] = "efe3d2ddb5a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_hotels_admin_id_users", "hotels", type_="foreignkey"
    )
    op.drop_column("hotels", "admin_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels",
        sa.Column(
            "admin_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_hotels_admin_id_users", "hotels", "users", ["admin_id"], ["id"]
    )
    # ### end Alembic commands ###
