"""empty message

Revision ID: 8e70a00a8b92
Revises: 341c982d0dba
Create Date: 2025-02-18 13:17:07.683494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e70a00a8b92"
down_revision: Union[str, None] = "341c982d0dba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_hotels_city_id_citys", "hotels", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_hotels_city_id_citys"), "hotels", "citys", ["city_id"], ["id"]
    )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", name="role_types"),
            server_default=sa.text("'USER'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_constraint(
        op.f("fk_hotels_city_id_citys"), "hotels", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_hotels_city_id_citys",
        "hotels",
        "citys",
        ["city_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
