"""empty message

Revision ID: b76b67ab21dd
Revises: 84eedc3e70c0
Create Date: 2025-03-09 02:23:20.757597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b76b67ab21dd"
down_revision: Union[str, None] = "84eedc3e70c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_role", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_role", "users", ["role"])
    # ### end Alembic commands ###
