"""empty message

Revision ID: 7d859de4bb0c
Revises: a3daf863bc83
Create Date: 2025-02-28 15:47:12.855339

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d859de4bb0c"
down_revision: Union[str, None] = "a3daf863bc83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations", sa.Column("latitude", sa.Float(), nullable=False)
    )
    op.add_column(
        "locations", sa.Column("longitude", sa.Float(), nullable=False)
    )
    op.drop_column("locations", "geocode_lat")
    op.drop_column("locations", "geocode_lng")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "geocode_lng",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "locations",
        sa.Column(
            "geocode_lat",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("locations", "longitude")
    op.drop_column("locations", "latitude")
    # ### end Alembic commands ###
