"""empty message

Revision ID: 85bde27ca8f4
Revises: 341c982d0dba
Create Date: 2025-02-18 12:56:58.219041

"""

from typing import Sequence, Union
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85bde27ca8f4"
down_revision: Union[str, None] = "341c982d0dba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_hotels_city_id_citys", "hotels", type_="foreignkey")
    op.drop_column("hotels", "city_id")
    op.add_column(
        "users",
        sa.Column(
            "role",
            sqlalchemy_utils.types.choice.ChoiceType(
                choices=[
                    ("USER", "user"),
                    ("ADMIN", "admin"),
                ]
            ),
            server_default="USER",
        ),
    ),

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.add_column(
        "hotels",
        sa.Column("city_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_hotels_city_id_citys",
        "hotels",
        "citys",
        ["city_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
