"""empty message

Revision ID: f02c12f76404
Revises: 8b3d1a8044f7
Create Date: 2025-03-08 23:42:51.937285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f02c12f76404"
down_revision: Union[str, None] = "8b3d1a8044f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partners",
        sa.Column(
            "is_active", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "partners",
        sa.Column(
            "is_verified", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "partners",
        sa.Column(
            "is_fully_registered",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.drop_column("partners", "password")
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("SUPERADMIN", "USER", name="user_role_types"),
            server_default=sa.text("'USER'"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", name="gender_types"),
        nullable=True,
        existing_server_default=sa.text("'MALE'::gender_types"),
    )
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_role"), "users", ["role"])
    op.drop_column("users", "email")
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_superuser",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(op.f("uq_users_role"), "users", type_="unique")
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    op.alter_column(
        "users",
        "gender",
        existing_type=postgresql.ENUM("MALE", "FEMALE", name="gender_types"),
        nullable=False,
        existing_server_default=sa.text("'MALE'::gender_types"),
    )
    op.drop_column("users", "role")
    op.add_column(
        "partners",
        sa.Column(
            "password", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("partners", "is_fully_registered")
    op.drop_column("partners", "is_verified")
    op.drop_column("partners", "is_active")
    # ### end Alembic commands ###
