"""empty message

Revision ID: 341c982d0dba
Revises: 5078bd980804
Create Date: 2025-02-18 11:58:24.918349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "341c982d0dba"
down_revision: Union[str, None] = "5078bd980804"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_citys_name"), "citys", ["name"])
    op.drop_constraint(
        "fk_citys_country_id_countrys", "citys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_citys_country_id_countrys"),
        "citys",
        "countrys",
        ["country_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(op.f("uq_countrys_name"), "countrys", ["name"])
    op.add_column("hotels", sa.Column("city_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_hotels_city_id_citys"),
        "hotels",
        "citys",
        ["city_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_hotels_city_id_citys"), "hotels", type_="foreignkey"
    )
    op.drop_column("hotels", "city_id")
    op.drop_constraint(op.f("uq_countrys_name"), "countrys", type_="unique")
    op.drop_constraint(
        op.f("fk_citys_country_id_countrys"), "citys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_citys_country_id_countrys",
        "citys",
        "countrys",
        ["country_id"],
        ["id"],
    )
    op.drop_constraint(op.f("uq_citys_name"), "citys", type_="unique")
    # ### end Alembic commands ###
