"""empty message

Revision ID: efe3d2ddb5a0
Revises: 13fd5c4bff15
Create Date: 2025-02-20 02:15:02.675275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efe3d2ddb5a0"
down_revision: Union[str, None] = "13fd5c4bff15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels", sa.Column("coordinate_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_hotels_coordinate_id_coordinates"),
        "hotels",
        "coordinates",
        ["coordinate_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_hotels_coordinate_id_coordinates"),
        "hotels",
        type_="foreignkey",
    )
    op.drop_column("hotels", "coordinate_id")
    # ### end Alembic commands ###
