"""empty message

Revision ID: 84eedc3e70c0
Revises: 85ec18331bf6
Create Date: 2025-03-09 02:21:50.933834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84eedc3e70c0"
down_revision: Union[str, None] = "85ec18331bf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "country_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "country_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
