"""empty message

Revision ID: f839ceeec904
Revises: 37eb45704f5e
Create Date: 2025-03-08 13:06:57.290462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f839ceeec904"
down_revision: Union[str, None] = "37eb45704f5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("check_in_from", sa.Time(), nullable=False),
        sa.Column("check_in_until", sa.Time(), nullable=True),
        sa.Column("check_out_from", sa.Time(), nullable=False),
        sa.Column("check_out_until", sa.Time(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name=op.f("fk_rules_hotel_id_hotels")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
    )
    op.create_index(op.f("ix_rules_id"), "rules", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rules_id"), table_name="rules")
    op.drop_table("rules")
    # ### end Alembic commands ###
