"""empty message

Revision ID: 0555955ef14e
Revises: 
Create Date: 2025-02-21 00:36:31.678368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0555955ef14e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_coordinates_id", table_name="coordinates")
    op.drop_table("coordinates")
    op.drop_table("room_amenity_association")
    op.drop_index("ix_amenities_id", table_name="amenities")
    op.drop_table("amenities")
    op.drop_table("hotel_amenity_association")
    op.drop_index("ix_amenity_categories_id", table_name="amenity_categories")
    op.drop_table("amenity_categories")
    op.add_column(
        "bookings",
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "CANCELLED", name="bookingstatus"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
    )
    op.add_column(
        "cities", sa.Column("slug", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "cities", sa.Column("properties_count", sa.Integer(), nullable=False)
    )
    op.add_column("cities", sa.Column("aero_lat", sa.Float(), nullable=False))
    op.add_column("cities", sa.Column("aero_lng", sa.Float(), nullable=False))
    op.add_column("cities", sa.Column("rail_lat", sa.Float(), nullable=False))
    op.add_column("cities", sa.Column("rail_lng", sa.Float(), nullable=False))
    op.add_column(
        "cities", sa.Column("image", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(op.f("uq_cities_slug"), "cities", ["slug"])
    op.drop_constraint(
        "fk_cities_country_id_countries", "cities", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_cities_country_id_countries"),
        "cities",
        "countries",
        ["country_id"],
        ["id"],
    )
    op.create_unique_constraint(
        "uq_hotel_amenity",
        "hotel_amenity_associations",
        ["hotel_id", "hotel_amenity_id"],
    )
    op.add_column(
        "hotels", sa.Column("location_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "fk_hotels_city_id_cities", "hotels", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_hotels_coordinate_id_coordinates", "hotels", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_hotels_location_id_locations"),
        "hotels",
        "locations",
        ["location_id"],
        ["id"],
    )
    op.drop_column("hotels", "coordinate_id")
    op.drop_column("hotels", "city_id")
    op.drop_column("hotels", "address")
    op.add_column(
        "locations", sa.Column("address", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "locations", sa.Column("geocode_lat", sa.Float(), nullable=False)
    )
    op.add_column(
        "locations", sa.Column("geocode_lng", sa.Float(), nullable=False)
    )
    op.drop_column("locations", "latitude")
    op.drop_column("locations", "longitude")
    op.create_unique_constraint(
        "uq_room_amenity",
        "room_amenity_associations",
        ["room_id", "room_amenity_id"],
    )
    op.drop_column("room_types", "description")
    op.add_column(
        "rooms", sa.Column("max_children", sa.Integer(), nullable=False)
    )
    op.add_column("rooms", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "rooms", sa.Column("preview_photo_url", sa.String(), nullable=True)
    )
    op.add_column(
        "rooms",
        sa.Column(
            "quantity", sa.Integer(), server_default="1", nullable=False
        ),
    )
    op.add_column(
        "rooms", sa.Column("base_price", sa.Numeric(), nullable=False)
    )
    op.drop_constraint("fk_rooms_hotel_id_hotels", "rooms", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_rooms_hotel_id_hotels"),
        "rooms",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    op.drop_column("rooms", "preview_photo_path")
    op.drop_column("rooms", "price_per_night")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column(
            "price_per_night",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "preview_photo_path",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("fk_rooms_hotel_id_hotels"), "rooms", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_rooms_hotel_id_hotels",
        "rooms",
        "hotels",
        ["hotel_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("rooms", "base_price")
    op.drop_column("rooms", "quantity")
    op.drop_column("rooms", "preview_photo_url")
    op.drop_column("rooms", "description")
    op.drop_column("rooms", "max_children")
    op.add_column(
        "room_types",
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        "uq_room_amenity", "room_amenity_associations", type_="unique"
    )
    op.add_column(
        "locations",
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "locations",
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("locations", "geocode_lng")
    op.drop_column("locations", "geocode_lat")
    op.drop_column("locations", "address")
    op.add_column(
        "hotels",
        sa.Column(
            "address",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "city_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "hotels",
        sa.Column(
            "coordinate_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_hotels_location_id_locations"), "hotels", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_hotels_coordinate_id_coordinates",
        "hotels",
        "coordinates",
        ["coordinate_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_hotels_city_id_cities", "hotels", "cities", ["city_id"], ["id"]
    )
    op.drop_column("hotels", "location_id")
    op.drop_constraint(
        "uq_hotel_amenity", "hotel_amenity_associations", type_="unique"
    )
    op.drop_constraint(
        op.f("fk_cities_country_id_countries"), "cities", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_cities_country_id_countries",
        "cities",
        "countries",
        ["country_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("uq_cities_slug"), "cities", type_="unique")
    op.drop_column("cities", "image")
    op.drop_column("cities", "rail_lng")
    op.drop_column("cities", "rail_lat")
    op.drop_column("cities", "aero_lng")
    op.drop_column("cities", "aero_lat")
    op.drop_column("cities", "properties_count")
    op.drop_column("cities", "slug")
    op.drop_column("bookings", "status")
    op.create_table(
        "amenity_categories",
        sa.Column(
            "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('amenity_categories_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_amenity_categories"),
        sa.UniqueConstraint("name", name="uq_amenity_categories_name"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_amenity_categories_id", "amenity_categories", ["id"], unique=True
    )
    op.create_table(
        "hotel_amenity_association",
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "amenity_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["amenity_id"],
            ["amenities.id"],
            name="fk_hotel_amenity_association_amenity_id_amenities",
        ),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
            name="fk_hotel_amenity_association_hotel_id_hotels",
        ),
        sa.PrimaryKeyConstraint(
            "hotel_id", "amenity_id", name="pk_hotel_amenity_association"
        ),
        sa.UniqueConstraint("hotel_id", "amenity_id", name="uq_hotel_amenity"),
    )
    op.create_table(
        "amenities",
        sa.Column(
            "name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_popular", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "payment_type",
            postgresql.ENUM(
                "FREE", "PAID", "PAID_SEPARATELY", name="paymenttype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "amenity_category_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["amenity_category_id"],
            ["amenity_categories.id"],
            name="fk_amenities_amenity_category_id_amenity_categories",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_amenities"),
        sa.UniqueConstraint("name", name="uq_amenities_name"),
    )
    op.create_index("ix_amenities_id", "amenities", ["id"], unique=True)
    op.create_table(
        "room_amenity_association",
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "room_amenity_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_amenity_id"],
            ["room_amenities.id"],
            name="fk_room_amenity_association_room_amenity_id_room_amenities",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
            name="fk_room_amenity_association_room_id_rooms",
        ),
        sa.PrimaryKeyConstraint(
            "room_id", "room_amenity_id", name="pk_room_amenity_association"
        ),
    )
    op.create_table(
        "coordinates",
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_coordinates"),
    )
    op.create_index("ix_coordinates_id", "coordinates", ["id"], unique=True)
    # ### end Alembic commands ###
