"""empty message

Revision ID: 25c712849651
Revises: 21ddc10db116
Create Date: 2025-02-20 02:39:00.856696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25c712849651"
down_revision: Union[str, None] = "21ddc10db116"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_hotels_slug", "hotels", type_="unique")
    op.drop_column("hotels", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels",
        sa.Column(
            "slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint("uq_hotels_slug", "hotels", ["slug"])
    # ### end Alembic commands ###
