"""empty message

Revision ID: 6665d567a028
Revises: 965065b5a333
Create Date: 2025-03-06 16:00:54.344684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6665d567a028"
down_revision: Union[str, None] = "965065b5a333"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cities",
        sa.Column("geocode_lng", sa.Float(), nullable=False, server_default="0"),
    )
    op.add_column(
        "cities",
        sa.Column("geocode_lat", sa.Float(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cities", "geocode_lat")
    op.drop_column("cities", "geocode_lng")
    # ### end Alembic commands ###
