"""empty message

Revision ID: b6f66a281ad6
Revises: 
Create Date: 2025-03-24 22:43:58.247349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6f66a281ad6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_hotel_amenity",
        "hotel_amenity_associations",
        ["hotel_id", "hotel_amenity_id"],
    )
    op.alter_column(
        "partners",
        "first_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "partners",
        "last_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    op.drop_column("partners", "password")
    op.create_unique_constraint(
        "uq_room_amenity",
        "room_amenity_associations",
        ["room_id", "room_amenity_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_room_amenity", "room_amenity_associations", type_="unique"
    )
    op.add_column(
        "partners",
        sa.Column(
            "password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "partners",
        "last_name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "partners",
        "first_name",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_constraint(
        "uq_hotel_amenity", "hotel_amenity_associations", type_="unique"
    )
    # ### end Alembic commands ###
