"""empty message

Revision ID: aeb8e6a2bbc6
Revises: 179189fe6b02
Create Date: 2025-03-12 18:32:15.395776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aeb8e6a2bbc6"
down_revision: Union[str, None] = "179189fe6b02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bookings_id", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index("ix_rules_id", table_name="rules")
    op.drop_table("rules")
    op.add_column(
        "rooms", sa.Column("room_type_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_rooms_room_type_id_room_types"),
        "rooms",
        "room_types",
        ["room_type_id"],
        ["id"],
    )
    op.drop_column("rooms", "room_type_variant_id")
    op.drop_column("rooms", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "room_type_variant_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_rooms_room_type_id_room_types"), "rooms", type_="foreignkey"
    )
    op.drop_column("rooms", "room_type_id")
    op.create_table(
        "rules",
        sa.Column(
            "check_in_from", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_in_until", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "check_out_from", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_out_until", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "hotel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"], ["hotels.id"], name="fk_rules_hotel_id_hotels"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_rules"),
    )
    op.create_index("ix_rules_id", "rules", ["id"], unique=True)
    op.create_table(
        "bookings",
        sa.Column(
            "check_in_date", sa.DATE(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "check_out_date", sa.DATE(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "CONFIRMED", "CANCELLED", name="bookingstatus"
            ),
            server_default=sa.text("'PENDING'::bookingstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "total_days", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guest_quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "check_in_date < check_out_date",
            name="ck_bookings_check_in_date_before_check_out_date",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name="fk_bookings_room_id_rooms"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_bookings_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_bookings"),
    )
    op.create_index("ix_bookings_id", "bookings", ["id"], unique=True)
    # ### end Alembic commands ###
